import { db } from '$lib/database';
import { error } from '@sveltejs/kit';
import { SqliteError } from 'better-sqlite3';
import type { DB } from 'kysely-codegen';

export async function exists(table: keyof DB, id: number) {
	const record = await db.selectFrom(table).select('id').where('id', '=', id).execute();
	if (!record) throw error(404, 'Department not found');
}

export function sqliteCustomErrorMap(err: unknown) {
	if (err instanceof SqliteError) {
		if (err.code === SqliteErrorCode.SQLITE_CONSTRAINT_UNIQUE) {
			const property = err.message.split(':')[1].replace('.', ' ');
			throw error(409, `${property} already exists`);
		}
	}
}

enum SqliteErrorCode {
	SQLITE_OK = 'SQLITE_OK',
	SQLITE_ERROR = 'SQLITE_ERROR',
	SQLITE_INTERNAL = 'SQLITE_INTERNAL',
	SQLITE_PERM = 'SQLITE_PERM',
	SQLITE_ABORT = 'SQLITE_ABORT',
	SQLITE_BUSY = 'SQLITE_BUSY',
	SQLITE_LOCKED = 'SQLITE_LOCKED',
	SQLITE_NOMEM = 'SQLITE_NOMEM',
	SQLITE_READONLY = 'SQLITE_READONLY',
	SQLITE_INTERRUPT = 'SQLITE_INTERRUPT',
	SQLITE_IOERR = 'SQLITE_IOERR',
	SQLITE_CORRUPT = 'SQLITE_CORRUPT',
	SQLITE_NOTFOUND = 'SQLITE_NOTFOUND',
	SQLITE_FULL = 'SQLITE_FULL',
	SQLITE_CANTOPEN = 'SQLITE_CANTOPEN',
	SQLITE_PROTOCOL = 'SQLITE_PROTOCOL',
	SQLITE_EMPTY = 'SQLITE_EMPTY',
	SQLITE_SCHEMA = 'SQLITE_SCHEMA',
	SQLITE_TOOBIG = 'SQLITE_TOOBIG',
	SQLITE_CONSTRAINT = 'SQLITE_CONSTRAINT',
	SQLITE_MISMATCH = 'SQLITE_MISMATCH',
	SQLITE_MISUSE = 'SQLITE_MISUSE',
	SQLITE_NOLFS = 'SQLITE_NOLFS',
	SQLITE_AUTH = 'SQLITE_AUTH',
	SQLITE_FORMAT = 'SQLITE_FORMAT',
	SQLITE_RANGE = 'SQLITE_RANGE',
	SQLITE_NOTADB = 'SQLITE_NOTADB',
	SQLITE_NOTICE = 'SQLITE_NOTICE',
	SQLITE_WARNING = 'SQLITE_WARNING',
	SQLITE_ROW = 'SQLITE_ROW',
	SQLITE_DONE = 'SQLITE_DONE',
	SQLITE_IOERR_READ = 'SQLITE_IOERR_READ',
	SQLITE_IOERR_SHORT_READ = 'SQLITE_IOERR_SHORT_READ',
	SQLITE_IOERR_WRITE = 'SQLITE_IOERR_WRITE',
	SQLITE_IOERR_FSYNC = 'SQLITE_IOERR_FSYNC',
	SQLITE_IOERR_DIR_FSYNC = 'SQLITE_IOERR_DIR_FSYNC',
	SQLITE_IOERR_TRUNCATE = 'SQLITE_IOERR_TRUNCATE',
	SQLITE_IOERR_FSTAT = 'SQLITE_IOERR_FSTAT',
	SQLITE_IOERR_UNLOCK = 'SQLITE_IOERR_UNLOCK',
	SQLITE_IOERR_RDLOCK = 'SQLITE_IOERR_RDLOCK',
	SQLITE_IOERR_DELETE = 'SQLITE_IOERR_DELETE',
	SQLITE_IOERR_BLOCKED = 'SQLITE_IOERR_BLOCKED',
	SQLITE_IOERR_NOMEM = 'SQLITE_IOERR_NOMEM',
	SQLITE_IOERR_ACCESS = 'SQLITE_IOERR_ACCESS',
	SQLITE_IOERR_CHECKRESERVEDLOCK = 'SQLITE_IOERR_CHECKRESERVEDLOCK',
	SQLITE_IOERR_LOCK = 'SQLITE_IOERR_LOCK',
	SQLITE_IOERR_CLOSE = 'SQLITE_IOERR_CLOSE',
	SQLITE_IOERR_DIR_CLOSE = 'SQLITE_IOERR_DIR_CLOSE',
	SQLITE_IOERR_SHMOPEN = 'SQLITE_IOERR_SHMOPEN',
	SQLITE_IOERR_SHMSIZE = 'SQLITE_IOERR_SHMSIZE',
	SQLITE_IOERR_SHMLOCK = 'SQLITE_IOERR_SHMLOCK',
	SQLITE_IOERR_SHMMAP = 'SQLITE_IOERR_SHMMAP',
	SQLITE_IOERR_SEEK = 'SQLITE_IOERR_SEEK',
	SQLITE_IOERR_DELETE_NOENT = 'SQLITE_IOERR_DELETE_NOENT',
	SQLITE_IOERR_MMAP = 'SQLITE_IOERR_MMAP',
	SQLITE_IOERR_GETTEMPPATH = 'SQLITE_IOERR_GETTEMPPATH',
	SQLITE_IOERR_CONVPATH = 'SQLITE_IOERR_CONVPATH',
	SQLITE_IOERR_VNODE = 'SQLITE_IOERR_VNODE',
	SQLITE_IOERR_AUTH = 'SQLITE_IOERR_AUTH',
	SQLITE_LOCKED_SHAREDCACHE = 'SQLITE_LOCKED_SHAREDCACHE',
	SQLITE_BUSY_RECOVERY = 'SQLITE_BUSY_RECOVERY',
	SQLITE_BUSY_SNAPSHOT = 'SQLITE_BUSY_SNAPSHOT',
	SQLITE_CANTOPEN_NOTEMPDIR = 'SQLITE_CANTOPEN_NOTEMPDIR',
	SQLITE_CANTOPEN_ISDIR = 'SQLITE_CANTOPEN_ISDIR',
	SQLITE_CANTOPEN_FULLPATH = 'SQLITE_CANTOPEN_FULLPATH',
	SQLITE_CANTOPEN_CONVPATH = 'SQLITE_CANTOPEN_CONVPATH',
	SQLITE_CORRUPT_VTAB = 'SQLITE_CORRUPT_VTAB',
	SQLITE_READONLY_RECOVERY = 'SQLITE_READONLY_RECOVERY',
	SQLITE_READONLY_CANTLOCK = 'SQLITE_READONLY_CANTLOCK',
	SQLITE_READONLY_ROLLBACK = 'SQLITE_READONLY_ROLLBACK',
	SQLITE_READONLY_DBMOVED = 'SQLITE_READONLY_DBMOVED',
	SQLITE_ABORT_ROLLBACK = 'SQLITE_ABORT_ROLLBACK',
	SQLITE_CONSTRAINT_CHECK = 'SQLITE_CONSTRAINT_CHECK',
	SQLITE_CONSTRAINT_COMMITHOOK = 'SQLITE_CONSTRAINT_COMMITHOOK',
	SQLITE_CONSTRAINT_FOREIGNKEY = 'SQLITE_CONSTRAINT_FOREIGNKEY',
	SQLITE_CONSTRAINT_FUNCTION = 'SQLITE_CONSTRAINT_FUNCTION',
	SQLITE_CONSTRAINT_NOTNULL = 'SQLITE_CONSTRAINT_NOTNULL',
	SQLITE_CONSTRAINT_PRIMARYKEY = 'SQLITE_CONSTRAINT_PRIMARYKEY',
	SQLITE_CONSTRAINT_TRIGGER = 'SQLITE_CONSTRAINT_TRIGGER',
	SQLITE_CONSTRAINT_UNIQUE = 'SQLITE_CONSTRAINT_UNIQUE',
	SQLITE_CONSTRAINT_VTAB = 'SQLITE_CONSTRAINT_VTAB',
	SQLITE_CONSTRAINT_ROWID = 'SQLITE_CONSTRAINT_ROWID',
	SQLITE_NOTICE_RECOVER_WAL = 'SQLITE_NOTICE_RECOVER_WAL',
	SQLITE_NOTICE_RECOVER_ROLLBACK = 'SQLITE_NOTICE_RECOVER_ROLLBACK',
	SQLITE_WARNING_AUTOINDEX = 'SQLITE_WARNING_AUTOINDEX',
	SQLITE_AUTH_USER = 'SQLITE_AUTH_USER',
	SQLITE_OK_LOAD_PERMANENTLY = 'SQLITE_OK_LOAD_PERMANENTLY'
}
